/**
 * PLANO - Treino base do programa (exercicios e series por dia da semana).
 *
 * Formato: { seg: { t: nomeTreino, ex: [[nome, grupoMuscular, series, min, max], ...] }, ... }
 */

const PLANO = {"seg": {"t": "Push A", "ex": [["Supino com Halteres", "Peito", 4, 6, 12], ["Supino Inclinado / Variação", "Peito", 3, 8, 15], ["Desenvolvimento com Halteres", "Ombros", 3, 8, 12], ["Elevação Lateral", "Ombros", 4, 12, 20], ["Tríceps Francês", "Tríceps", 3, 10, 15], ["Tríceps Testa", "Tríceps", 3, 10, 15], ["Abdominal", "Abdômen", 3, 12, 20]]}, "ter": {"t": "Pull A", "ex": [["Remada Curvada com Halteres", "Costas", 4, 8, 12], ["Remada Unilateral", "Costas", 3, 8, 15], ["Pullover com Halter", "Costas", 3, 10, 15], ["Crucifixo Inverso", "Ombro Posterior", 4, 12, 20], ["Rosca Alternada", "Bíceps", 3, 8, 12], ["Rosca Martelo", "Bíceps", 3, 10, 15]]}, "qua": {"t": "Legs A", "ex": [["Agachamento Goblet", "Quadríceps", 4, 10, 15], ["Afundo com Halteres", "Quadríceps", 3, 8, 12], ["Cadeira Extensora", "Quadríceps", 4, 10, 15], ["Terra Romeno com Halteres", "Posterior", 4, 8, 12], ["Elevação Pélvica", "Posterior", 3, 10, 15], ["Panturrilha", "Panturrilha", 4, 12, 20], ["Abdominal", "Abdômen", 3, 12, 20]]}, "qui": {"t": "Superior B", "ex": [["Supino com Halteres", "Peito", 3, 8, 12], ["Crucifixo com Halteres", "Peito", 3, 10, 15], ["Remada Unilateral", "Costas", 3, 10, 15], ["Remada Curvada", "Costas", 3, 8, 12], ["Elevação Lateral", "Ombros", 4, 12, 20], ["Crucifixo Inverso", "Ombro Posterior", 3, 12, 20], ["Rosca Martelo", "Bíceps", 3, 10, 15], ["Tríceps Francês", "Tríceps", 3, 10, 15]]}, "sex": {"t": "Legs B + Braços", "ex": [["Agachamento Búlgaro", "Quadríceps", 4, 8, 12], ["Cadeira Extensora", "Quadríceps", 4, 12, 20], ["Terra Romeno", "Posterior", 4, 8, 12], ["Elevação Pélvica", "Posterior", 3, 10, 15], ["Panturrilha", "Panturrilha", 4, 15, 25], ["Rosca Alternada", "Bíceps", 3, 10, 15], ["Tríceps Francês", "Tríceps", 3, 10, 15], ["Abdominal", "Abdômen", 3, 12, 20]]}};

export { PLANO };
